-- 107번 직원의 이름과 월급 조회
CREATE PROCEDURE GET_EMP_SAL(
    IN_DPTID NUMBER
)
IS
    V_ENAME VARCHAR(46);
    V_SAL NUMBER(8,2);
    BEGIN
        SELECT FIRST_NAME || ' ' || LAST_NAME, SALARY
        INTO V_ENAME, V_SAL
        FROM HR.EMPLOYEES
        WHERE DEPARTMENT_ID = IN_DPTID;
        
        DBMS_OUTPUT.PUT_LINE('직원명: ' || V_ENAME);
        DBMS_OUTPUT.PUT_LINE('월급: ' || V_SAL);
    END;
/

SET SERVEROUTPUT ON;
CALL GET_EMP_SAL(10);

CREATE OR REPLACE PROCEDURE EMP_LIST(
    IN_DPTID NUMBER,
    O_CUR OUT SYS_REFCURSOR
)
IS 
    BEGIN
        OPEN O_CUR FOR
            SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL
            FROM EMPLOYEES
            WHERE DEPARTMENT_ID = IN_DPTID;
    END;
/
VARIABLE O_CUR REFCURSOR;
EXECUTE EMP_LIST(50, :O_CUR);
PRINT O_CUR;
    